version: '3'

services:
  web:
    container_name: {{name}}-web
    image: mediasignal/typo3-dev:8.7.8
    depends_on:
      - db
    ports:
      - 8000:80
    environment:
      TYPO3_CONTEXT: Development
    volumes:
      - ./web/fileadmin/:/var/www/html/fileadmin
      - ./web/typo3conf/:/var/www/html/typo3conf
      - ./web/typo3temp/:/var/www/html/typo3temp
      - ./web/uploads/:/var/www/html/uploads
      - ./web/composer.json:/var/www/html/composer.json
      - ./web/composer.lock:/var/www/html/composer.lock

  db:
    container_name: {{name}}-db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: typo3
    volumes:
      - ./database:/database
